# Generated by Django 3.2.7 on 2021-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
                ('rent_date', models.DateField(verbose_name='')),
            ],
        ),
    ]
