# Generated by Django 3.2.7 on 2021-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='', upload_to='vehicleservice/images'),
        ),
    ]
